import React from 'react'

import { PageLayout } from 'components/ui'
import type { Metadata } from 'next'
import 'theme/global.css'

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return <PageLayout>{children}</PageLayout>
}
