import React from 'react'

import { FullPageLayout, PageLayout } from 'components/ui'
import type { Metadata } from 'next'
import 'theme/global.css'

export const metadata: Metadata = {
  title: 'Login | Ivan Bondar',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <PageLayout>
      <FullPageLayout>{children}</FullPageLayout>
    </PageLayout>
  )
}
