import React from 'react'

import {
  AdminContentPositioner,
  AdminPageContentWrapper,
  AdminPageWrapper,
} from 'app/admin/components/AdminLayout.styles'
import { SideBar } from 'app/admin/components/SideBar'
import { TopNav } from 'app/admin/components/TopNav'
import { AuthGuard } from 'app/admin/guards/AuthGuard'
import { Flex, PageLayout } from 'components/ui'
import type { Metadata } from 'next'
import 'theme/global.css'

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <PageLayout>
      <AuthGuard>
        <AdminPageWrapper>
          <TopNav />
          <Flex flex={1}>
            <SideBar />
            <AdminContentPositioner>
              <AdminPageContentWrapper>{children}</AdminPageContentWrapper>
            </AdminContentPositioner>
          </Flex>
        </AdminPageWrapper>
      </AuthGuard>
    </PageLayout>
  )
}
