import React from 'react'

import { Footer } from 'app/(website)/components/Footer/Footer'
import { Menu } from 'app/(website)/components/Menu/Menu'
import { PageWrapper } from 'app/(website)/components/styles'
import { GetInTouch } from 'components/GetInTouch/GetInTouch'
import { Stack } from 'components/ui'
import StyledComponentsRegistry from 'lib/registry'
import type { Metadata } from 'next'
import ThemeProvider from 'theme/ThemeProvider'
import 'theme/global.css'
import { GlobalStyles } from 'theme/globalStyles'
import { inter } from 'utils/fonts'

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <StyledComponentsRegistry>
      <ThemeProvider>
        <GlobalStyles />
        <html lang="en">
          <body className={inter.className}>
            <PageWrapper>
              <Menu />
              <Stack gap="spacing96">
                <main>{children}</main>
                <Stack gap="spacing48">
                  <GetInTouch />
                  <Footer />
                </Stack>
              </Stack>
            </PageWrapper>
          </body>
        </html>
      </ThemeProvider>
    </StyledComponentsRegistry>
  )
}
